### PR TITLE
GitHub Action to discover typos with codespell

### PR DESCRIPTION
**Pull request by cclauss**
https://pypi.org/project/codespell

Test results: https://github.com/cclauss/jython.github.io/actions
```
2
./jython.github.io/registry.md:7: envrionment ==> environment
./jython.github.io/registry.md:11: formated ==> formatted
```

### CODE REVIEW

**Review by yusufadell — COMMENTED** [review]
Inspiring, i'll Start every project of mine with that action in it...

**Comment by jeff5** [comment]
Seems reasonable to me. Thanks.

**Comment by jeff5** [comment]
@cclauss : I think I expected this to run when merged, but it didn't. Am I missing something?

**Comment by cclauss** [comment]
Looks like it will run upon your approval of #26.

**Comment by jeff5** [comment]
If it runs on subsequent pushes and PRs, that's fine. I was obviously wrong to expect it to run on the commit that adds it.

`codespell` takes the interesting approach of trying to catalogue misspellings, rather than using a dictionary of correctly spelled words. If not 100% successful, it makes a change for the errors to be mostly in the other direction (not constantly complaining about English spellings or words it doesn't know).

I'll also look at https://github.com/jython/jython/pull/179.

**Comment by cclauss** [comment]
Codespell is good at off-by-one typos like a missing letter or two transposed letters but it is certainly not a full spellchecker.  The upside is that it is astoundingly fast even on a massive repo of text.

**Pull request merged**
