### PR TITLE
Minor change to README.md

### PR DESCRIPTION
**Pull request by cclauss**
The GitHub Action runs here https://github.com/jython/jython.github.io/actions/workflows/codespell.yml

### CODE REVIEW

**Comment by cclauss** [comment]
Runs on my fork.

**Comment by cclauss** [comment]
Seems like it with run here https://github.com/jython/jython.github.io/actions if you approve below.

**Comment by jeff5** [comment]
Yes, the codespell ran ok on the PR. I think it was just that they don't when first added (which makes testing a new one difficult).

**Comment by cclauss** [comment]
It ran on **my fork** so I could see that the tests passed.  https://github.com/cclauss/jython.github.io/actions

**Pull request closed without merging**
