### PR TITLE
Updated links to reflect move to github.

### PR DESCRIPTION
**Pull request by Stewori**

### CODE REVIEW

**Comment by Stewori** [comment]
The additional nesting level might not be supported. So far I wasn't able to set up jekyll locally to test this. This is a hassle because my system ruby is too old...

**Comment by adamburkegh** [comment]
I just gave it a quick test locally with this patch, and the stuff under the new Legacy submenu didn't actually work. It just got a Legacy entry with an empty anchor and no sub items. So hold off merging I guess.  The other changes behaved themselves.

**Comment by Stewori** [comment]
I will create a page similar to links, holding the legacy links.

**Comment by Stewori** [comment]
This should be workable now and I finally managed to test it locally. We can leave it pending for a while until @jeff5 confirms that the jython/jython repo is sound.

**Comment by Stewori** [comment]
To me, this sounds like we can merge it now. It occurred to me that the new Legacy-dev page might look better with some slight descriptions of the links but I think it's good for now. We can polish it at any time if we decide to.

**Pull request merged**
